---
title: "STAT 432 Final Project -- Random Forest"
author: "Gwendolyn Jarrold"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(corrplot)
library(rpart)
library(rpart.plot)
library(randomForest)
library(dplyr)
library(ggplot2)
source("TC.R")
```

## Summary Statistics

```{r}
drug_cons_num <- read.csv("drug_consumption_numeric.csv")

drug_cons_num$gender <- as.factor(drug_cons_num$gender)
drug_cons_num$country <- as.factor(drug_cons_num$country)
drug_cons_num$ethnicity <- as.factor(drug_cons_num$ethnicity)
drug_cons_num$choc <- as.factor(drug_cons_num$choc)

summary(drug_cons_num)
```

```{r}
ggplot(data = drug_cons_num, aes(x = choc, group = gender, color = gender, fill = gender)) + 
  geom_bar(position = "dodge", alpha = 0.7) + 
  ggtitle("Frequency of Chocolate Consumption by Gender") + 
  ylab("Frequency") + 
  xlab("Chocolate Consumption")
```

```{r}
ggplot(data = drug_cons_num, aes(x = choc, y = age)) + 
  geom_jitter(width = 0.25, height = 0.25, alpha = 0.4, color = "purple") + 
  ggtitle("Chocolate Consumption by Age") + 
  ylab("Age Level") + 
  xlab("Chocolate Consumption")
```

```{r}
corrplot(cor(drug_cons_num[, 6:10]))
```

## Random Forest (Numeric Age and Education)  

```{r}
set.seed(432)

# Using default parameter values: 
choc_rf_default <- randomForest(choc ~ ., data = drug_cons_num, importance = TRUE)
choc_rf_default

choc_rf_def_confmat <- t(choc_rf_default$confusion[, -8])
TC(choc_rf_def_confmat)
```

```{r}
tuning_par <- expand.grid("ntree" = seq(from = 100, to = 1000, by = 50), 
                         "nodesize" = seq(from = 1, to = 10, by = 1), 
                         "mtry" = seq(from = 1, to = 10, by = 1))

TC_rf <- rep(NA, nrow(tuning_par))
```

```{r}
set.seed(432)

# Tuning the ntree, mtry, and nodesize parameters:

for (k in seq_along(TC_rf)) {
  choc_rf <- randomForest(choc ~ ., data = drug_cons_num, 
                          ntree = tuning_par$ntree[k], 
                          nodesize = tuning_par$nodesize[k], 
                          mtry = tuning_par$mtry[k])
  TC_rf[k] <- TC(t(choc_rf$confusion[, -8]))
}

rf_tune <- cbind(tuning_par, TC_rf)
```

```{r}
rf_best <- rf_tune[which.min(rf_tune$TC_rf), ]
rf_best
```

```{r}
rf_tune_mtry <- rf_tune %>% group_by(mtry)  %>%
                    summarise(mean_TC = mean(TC_rf), .groups = 'drop')

ggplot(data = rf_tune, aes(x = mtry, y = TC_rf)) + 
  geom_point(alpha = 0.3, color = "darkgreen") + 
  ggtitle("Number of Variables Sampled at Each Split (mtry) vs. TC") + 
  xlab("Number of Variables Randomly Sampled at Each Split") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 1, to = 10, by = 1)) + 
  geom_point(data = rf_tune_mtry, aes(x = mtry, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
rf_tune_nodesize <- rf_tune %>% group_by(nodesize)  %>%
                    summarise(mean_TC = mean(TC_rf), .groups = 'drop')

ggplot(data = rf_tune, aes(x = nodesize, y = TC_rf)) + 
  geom_point(alpha = 0.3, color = "maroon") + 
  ggtitle("Minimum Size of Terminal Nodes (nodesize) vs. TC") + 
  xlab("Minimum Size of Terminal Nodes") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 1, to = 10, by = 1)) + 
  geom_point(data = rf_tune_nodesize, aes(x = nodesize, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
rf_tune_ntree <- rf_tune %>% group_by(ntree)  %>%
                    summarise(mean_TC = mean(TC_rf), .groups = 'drop')

ggplot(data = rf_tune, aes(x = ntree, y = TC_rf)) + 
  geom_point(alpha = 0.3, color = "darkblue") + 
  ggtitle("Number of Trees (ntree) vs. TC") + 
  xlab("Number of Trees") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 100, to = 1000, by = 50)) + 
  geom_point(data = rf_tune_ntree, aes(x = ntree, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
set.seed(432)

# Tuned random forest model 
choc_rf_tuned <- randomForest(choc ~ ., data = drug_cons_num, 
                              ntree =  rf_best$ntree,
                              nodesize = rf_best$nodesize,
                              mtry = rf_best$mtry, 
                              importance = TRUE)
choc_rf_tuned

choc_rf_tuned_confmat <- t(choc_rf_tuned$confusion[, -8])
```

```{r}
choc_rf_tuned$importance
```

```{r}
choc_rf_tuned_confmat
TC(choc_rf_tuned_confmat)
```


## Bagging (Numeric Age and Education)  

```{r}
set.seed(432)

# Using default parameter values: 
choc_bag_default <- randomForest(choc ~ ., data = drug_cons_num, mtry = 10, 
                                 importance = TRUE)
choc_bag_default

choc_bag_def_confmat <- t(choc_bag_default$confusion[, -8])
TC(choc_bag_def_confmat)
```

```{r}
tuning_par2 <- expand.grid("ntree" = seq(from = 100, to = 1500, by = 50), 
                         "nodesize" = seq(from = 1, to = 20, by = 1))

TC_bag <- rep(NA, nrow(tuning_par2))
```

```{r}
set.seed(432)

# Tuning the ntree and nodesize parameters:

for (k in seq_along(TC_bag)) {
  choc_bag <- randomForest(choc ~ ., data = drug_cons_num, 
                           ntree = tuning_par2$ntree[k], 
                           nodesize = tuning_par2$nodesize[k], 
                           mtry = 10)
  TC_bag[k] <- TC(t(choc_bag$confusion[, -8]))
}

bag_tune <- cbind(tuning_par2, TC_bag)
```

```{r}
bag_best <- bag_tune[which.min(bag_tune$TC_bag), ]
bag_best
```

```{r}
bag_tune_nodesize <- bag_tune %>% group_by(nodesize)  %>%
                    summarise(mean_TC = mean(TC_bag), .groups = 'drop')

ggplot(data = bag_tune, aes(x = nodesize, y = TC_bag)) + 
  geom_point(alpha = 0.3, color = "maroon") + 
  ggtitle("Minimum Size of Terminal Nodes (nodesize) vs. TC") + 
  xlab("Minimum Size of Terminal Nodes") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 1, to = 20, by = 1)) + 
  geom_point(data = bag_tune_nodesize, aes(x = nodesize, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
bag_tune_ntree <- bag_tune %>% group_by(ntree)  %>%
                    summarise(mean_TC = mean(TC_bag), .groups = 'drop')

ggplot(data = bag_tune, aes(x = ntree, y = TC_bag)) + 
  geom_point(alpha = 0.3, color = "darkblue") + 
  ggtitle("Number of Trees (ntree) vs. TC") + 
  xlab("Number of Trees") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 100, to = 1500, by = 100)) + 
  geom_point(data = bag_tune_ntree, aes(x = ntree, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
set.seed(432)

# Tuned bagging model 
choc_bag_tuned <- randomForest(choc ~ ., data = drug_cons_num, 
                              ntree =  bag_best$ntree,
                              nodesize = bag_best$nodesize,
                              mtry = 10, 
                              importance = TRUE)
choc_bag_tuned

choc_bag_tuned_confmat <- t(choc_bag_tuned$confusion[, -8])
```

```{r}
choc_bag_tuned$importance
```

```{r}
choc_bag_tuned_confmat
TC(choc_bag_tuned_confmat)
```

## Random Forest (Factor Age and Education)

```{r}
drug_cons_num$age <- as.factor(drug_cons_num$age)
drug_cons_num$education <- as.factor(drug_cons_num$education)

summary(drug_cons_num)
```

```{r}
set.seed(432)

# Using default parameter values: 
choc_rf_default_f <- randomForest(choc ~ ., data = drug_cons_num, importance = TRUE)
choc_rf_default_f

choc_rf_def_f_confmat <- choc_rf_default_f$confusion[, -8]
TC(choc_rf_def_f_confmat)
```

```{r}
tuning_par3 <- expand.grid("ntree" = seq(from = 100, to = 1000, by = 50), 
                           "nodesize" = seq(from = 1, to = 10, by = 1), 
                           "mtry" = seq(from = 1, to = 10, by = 1))

TC_f_rf <- rep(NA, nrow(tuning_par3))
```

```{r}
set.seed(432)

# Tuning the ntree, mtry, and nodesize parameters:

for (k in seq_along(TC_f_rf)) {
  choc_rf <- randomForest(choc ~ ., data = drug_cons_num, 
                          ntree = tuning_par3$ntree[k], 
                          nodesize = tuning_par3$nodesize[k], 
                          mtry = tuning_par3$mtry[k])
  TC_f_rf[k] <- TC(t(choc_rf$confusion[, -8]))
}

rf_f_tune <- cbind(tuning_par3, TC_f_rf)
```

```{r}
rf_f_best <- rf_f_tune[which.min(rf_f_tune$TC_f_rf), ]
rf_f_best
```

```{r}
rf_f_tune_mtry <- rf_f_tune %>% group_by(mtry)  %>%
                    summarise(mean_TC = mean(TC_f_rf), .groups = 'drop')

ggplot(data = rf_f_tune, aes(x = mtry, y = TC_f_rf)) + 
  geom_point(alpha = 0.3, color = "darkgreen") + 
  ggtitle("Number of Variables Sampled at Each Split (mtry) vs. TC") + 
  xlab("Number of Variables Randomly Sampled at Each Split") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 1, to = 10, by = 1)) + 
  geom_point(data = rf_f_tune_mtry, aes(x = mtry, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
rf_f_tune_nodesize <- rf_f_tune %>% group_by(nodesize)  %>%
                    summarise(mean_TC = mean(TC_f_rf), .groups = 'drop')

ggplot(data = rf_f_tune, aes(x = nodesize, y = TC_f_rf)) + 
  geom_point(alpha = 0.3, color = "maroon") + 
  ggtitle("Minimum Size of Terminal Nodes (nodesize) vs. TC") + 
  xlab("Minimum Size of Terminal Nodes") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 1, to = 10, by = 1)) + 
  geom_point(data = rf_f_tune_nodesize, aes(x = nodesize, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
rf_f_tune_ntree <- rf_f_tune %>% group_by(ntree)  %>%
                    summarise(mean_TC = mean(TC_f_rf), .groups = 'drop')

ggplot(data = rf_f_tune, aes(x = ntree, y = TC_f_rf)) + 
  geom_point(alpha = 0.3, color = "darkblue") + 
  ggtitle("Number of Trees (ntree) vs. TC") + 
  xlab("Number of Trees") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 100, to = 1000, by = 50)) + 
  geom_point(data = rf_f_tune_ntree, aes(x = ntree, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
set.seed(432)

# Tuned random forest model 
choc_rf_f_tuned <- randomForest(choc ~ ., data = drug_cons_num, 
                              ntree =  rf_f_best$ntree,
                              nodesize = rf_f_best$nodesize,
                              mtry = rf_f_best$mtry, 
                              importance = TRUE)
choc_rf_f_tuned

choc_rf_f_tuned_confmat <- t(choc_rf_f_tuned$confusion[, -8])
```

```{r}
choc_rf_f_tuned$importance
```

```{r}
choc_rf_f_tuned_confmat
TC(choc_rf_f_tuned_confmat)
```

## Bagging (Factor Age and Education)

```{r}
set.seed(432)

# Using default parameter values: 
choc_bag_default_f <- randomForest(choc ~ ., data = drug_cons_num, mtry = 10, 
                                 importance = TRUE)
choc_bag_default_f

choc_bag_def_f_confmat <- t(choc_bag_default_f$confusion[, -8])
TC(choc_bag_def_f_confmat)
```

```{r}
tuning_par4 <- expand.grid("ntree" = seq(from = 100, to = 1500, by = 50), 
                         "nodesize" = seq(from = 1, to = 20, by = 1))

TC_f_bag <- rep(NA, nrow(tuning_par4))
```

```{r}
set.seed(432)

# Tuning the ntree and nodesize parameters:

for (k in seq_along(TC_f_bag)) {
  choc_bag <- randomForest(choc ~ ., data = drug_cons_num, 
                          ntree = tuning_par4$ntree[k], 
                          nodesize = tuning_par4$nodesize[k], 
                          mtry = 10)
  TC_f_bag[k] <- TC(t(choc_bag$confusion[, -8]))
}

bag_f_tune <- cbind(tuning_par4, TC_f_bag)
```

```{r}
bag_f_best <- bag_f_tune[which.min(bag_f_tune$TC_f_bag), ]
bag_f_best
```

```{r}
bag_f_tune_nodesize <- bag_f_tune %>% group_by(nodesize)  %>%
                    summarise(mean_TC = mean(TC_f_bag), .groups = 'drop')

ggplot(data = bag_f_tune, aes(x = nodesize, y = TC_f_bag)) + 
  geom_point(alpha = 0.3, color = "maroon") + 
  ggtitle("Minimum Size of Terminal Nodes (nodesize) vs. TC") + 
  xlab("Minimum Size of Terminal Nodes") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 1, to = 20, by = 1)) + 
  geom_point(data = bag_f_tune_nodesize, aes(x = nodesize, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
bag_f_tune_ntree <- bag_f_tune %>% group_by(ntree)  %>%
                    summarise(mean_TC = mean(TC_f_bag), .groups = 'drop')

ggplot(data = bag_f_tune, aes(x = ntree, y = TC_f_bag)) + 
  geom_point(alpha = 0.3, color = "darkblue") + 
  ggtitle("Number of Trees (ntree) vs. TC") + 
  xlab("Number of Trees") + 
  ylab("Total Misclassification Cost") + 
  scale_x_continuous(breaks = seq(from = 100, to = 1500, by = 100)) + 
  geom_point(data = bag_f_tune_ntree, aes(x = ntree, y = mean_TC), color = "black", size = 8, shape = "-")
```

```{r}
set.seed(432)

# Tuned bagging model 
choc_bag_f_tuned <- randomForest(choc ~ ., data = drug_cons_num, 
                                 ntree =  bag_f_best$ntree,
                                 nodesize = bag_f_best$nodesize,
                                 mtry = 10, 
                                 importance = TRUE)
choc_bag_f_tuned

choc_bag_f_tuned_confmat <- t(choc_bag_f_tuned$confusion[, -8])
```

```{r}
choc_bag_f_tuned$importance
```

```{r}
choc_bag_f_tuned_confmat
TC(choc_bag_f_tuned_confmat)
```

